---
# tasks file for upgrade-nextcloud
- name: "[NC-Upgrade] - Unzip is installed"
  package: name=unzip state=installed

- name: "Download & extract new Nextcloud version to /tmp."
  unarchive:
    copy: no
    src: "{{ nextcloud_full_url }}"
    dest: "/tmp/"
    creates: "/tmp/nextcloud/version.php"

- block:
    - name: "[NC-Upgrade] - Compare versions installed/new"
      script: "files/nc_check_versions.sh {{nextcloud_webroot}} /tmp/nextcloud/"
      register: nc_upgrade_check_versions
      changed_when: false
      failed_when: "{{nc_upgrade_check_versions.rc}} == 3"

    - fail: msg="{{nc_upgrade_check_versions.stdout}}"
      when: "{{nc_upgrade_check_versions.rc}} == 2"

  rescue:
    - name: "[NC-Upgrade] - Remove nextcloud archive files"
      file: path=/tmp/nextcloud state=absent

    - fail: msg="{{nc_upgrade_check_versions.stdout}}"

- block:
  - name: "[NC-Upgrade] - Nextcloud is in maintenance mode."
    become_user: "{{ nextcloud_websrv_user }}"
    command: php occ maintenance:mode --on
    args:
      chdir: "{{ nextcloud_webroot }}"

  - block:
      - include: tasks/nc_backup.yml
    rescue:
      - name: "[NC-Rescue] - Remove nextcloud backup directory."
        file: path={{nextcloud_backup_dir}} state=absent
        failed_when: true

  - name: "[NC-Upgrade] - webserver is stopped"
    service: name={{nextcloud_websrv}} state=stopped

  - block:
      - include: tasks/nc_inst_upgrade.yml
    rescue:
      - include: tasks/nc_rescue.yml
      - fail: msg="Upgrade installation failed."
  - name: "[NC-Upgrade] - webserver is started"
    service: name={{nextcloud_websrv}} state=started

  - block:
      - name: "[NC-Upgrade] - Run occ upgrade."
        become_user: "{{ nextcloud_websrv_user }}"
        command: php occ upgrade
        args:
          chdir: "{{ nextcloud_webroot }}"
        register: nc_upgrade_result
      - assert:
          that: "'update your PHP version' not in nc_upgrade_result.stdout"
    rescue:
      - include: tasks/nc_rescue.yml
      - fail: msg="{{nc_upgrade_result.stdout_lines}}"

  - name: "[NC-Upgrade] - Nextcloud is not in maintenance mode."
    become_user: "{{ nextcloud_websrv_user }}"
    command: php occ maintenance:mode --off
    args:
      chdir: "{{ nextcloud_webroot }}"

  - name: "[NC-Post-Upgrade]- Clean old nextcloud instance."
    file: name="{{nextcloud_webroot_old}}" state=absent
    when: nextcloud_upgrade_clean
  when: "{{nc_upgrade_check_versions.rc}} == 0"
